## Episode 178: *Mawaru Penguindrum* Colour Design Notes - Part 5: 3.11 At That Moment...

Drift ice seems to be coming to the northern sea, the Sea of Okhotsk coast, again this year.

Drift ice - this is amazing! I've been to Abashiri around this time three times so far to see the drift ice. The beautiful whiteness that completely fills the sea, the overwhelming mass beauty of ice that crashes against the shore and locks everything away. I really want everyone to see it at least once. Writing this, ah, I want to manage to go this year somehow. How many years has it been since last time? I keep narrowly missing the chance to go every year.

And the busier I get, the more I want to go! (←apparently escapist behavior)

Now, how is it really? Where's the schedule gap where I could actually go? (sweat)
Now then.

March 11th, 2:46 PM. Episode 3's art meeting had ended and I was having a late lunch at a French restaurant near the studio. Just as I finished eating and was chatting with the owner, it happened. A slow, long tremor began and gradually the amplitude grew larger. Wine glasses sliding off and shattering, wine bottles falling from shelves and breaking. Following the owner's instructions, I went out to the street and saw telephone poles swaying back and forth in an unbelievable way. The large amplitude that wasn't a direct hit made me immediately predict an epicenter off Chiba or Ibaraki. Or perhaps Tohoku? While the shaking continued, I checked information from Twitter on my iPhone. Tohoku offshore epicenter, Tokyo seismic intensity 5-strong (later corrected to 5-weak). Born and raised in Tokyo for nearly 48 years, it was the first earthquake of this scale I'd ever experienced.

When the major shaking subsided, I hurried back to the studio. What I was most worried about was my equipment. Would my EIZO 24-inch monitor COLOREDGE, my business tool, have fallen over? That was my primary concern. The staff room was on the 4th floor of the building. Since this floor had unpleasantly swayed greatly even during relatively small earthquakes before, I was especially worried about damage. Obviously the elevator was impossible right after the earthquake. I used the stairs to the 4th floor. As expected, the staff room was in quite a state. While calming down a northeastern production staff girl who was panicking because "I can't reach my family by phone," I looked around the staff room and what clearly remains in my memory is how the colour boxes stacked on the animation desks had fallen to the floor so cleanly and beautifully that visibility had greatly improved. Staff members picking up and organizing rough animation, timesheets, and setting copies scattered on the floor. Since it swayed roughly north-south, desks positioned facing north or south had their shelves catastrophically fallen. Director Ikuhara's, Assistant Director Yamazaki's, and Director Kaneko's desks were all positioned facing north and were in complete chaos. Incidentally, at that time Director Ikuhara was in the middle of a "script reading" with scriptwriter Igami and Assistant Director Yamazaki at a restaurant called "Bashamichi" in front of the station.

Fortunately, my desk area and equipment had no problems at all. I immediately gathered information on the internet, played NHK broadcast from the computer's external radio, and emailed my family to confirm safety. Then another big aftershock hit. I evacuated from the room with the production producer and others, and when it subsided we returned to the room. Then I couldn't believe the words I heard from the radio: "A 10-meter high tsunami..." What? And on the TV screen at Goto Keiji's desk were images of a town being swept away by muddy torrents...

For several days after that, production work continued sporadically at the site, but there was also an order from the production producer to "please work from home as much as possible for the time being," so main staff members worked primarily from home, only coming to the studio for meetings. I similarly worked primarily from home. But honestly, work was impossible to focus on, and I was completely affected deep in my heart by the disastrous images that were truly flooding us every day. I thought that was seriously dangerous. The images unknowingly penetrated deep into the heart and eroded one's feelings. As someone positioned at the edge of the video industry, I deeply impressed upon myself that I must be careful about such situations in various ways.

In any case, I was completely affected. The truth is that my desire to work or create anime was completely taken away. Somehow, when confronted with such real images, I even came to doubt creating fictional stories and videos, and for quite a while after I completely stopped wanting to watch movies. But this is dangerous! Anyway, back to daily life. If asked what I can do, it's only making anime. Anyway, continuing to work day by day as usual, one thing at a time. That's all I can do, and I convinced myself that doing so would surely be the most helpful thing for the world.

After things settled down somewhat, I thought about various things, and realised that if this had been the old days with paint work, it would have been a terrible situation. Paint bottles would probably have broken and scattered, with paint flowing out everywhere... Just thinking about it gives me chills. And I remembered something from about 20 years ago. There was a finishing company called Suzuki Animation Planning in Chiba that handled many Toei Animation (東映動画) works like the TV series *Fist of the North Star*, and they were hit by a somewhat large earthquake, the storage shelves for large paint bottles collapsed, and large quantities of cel paint bottles broke causing major damage. But nowadays everything requires electricity. Without electricity you can't use computers, without electricity you can't view a single image. This power problem would deal us another blow.

So while I went to the Mitaka studio pinpoint-style when there were meetings or checks to attend, then came the further trial of "planned blackouts." My home area of Nakano was in a blackout-exempt district, but the studio was firmly designated as a planned blackout target area. So inevitably daytime operating hours were restricted, and we generally shifted to nighttime work. But actually, despite being in a planned blackout area, the studio apparently never actually had a blackout, and we were irritated by the poor response from TEPCO and the government during those days.

Even so, I was glad we weren't involved in a work that was broadcasting. I heard that due to news programming, some broadcasts were postponed or suspended, and some works even needed content revisions, plus these planned blackouts. Some staff apparently had trouble even commuting, and whether revising or creating anew, it was quite a difficult period. While *Mawaru Penguindrum* was said to have no schedule, broadcast was still 4 months away, so by then things would probably be settled in various ways, we thought. However, our *Mawaru Penguindrum* was scheduled to debut at major March anime events, but ultimately all of those were canceled, and I honestly felt a bit anxious about the future.

In the end, throughout March after March 11th, there were 2-3 art board checks, 1 character colour check, 1 CG meeting, and direction meetings for 2 episodes. That was everything.

Such was March 2011.

*(12.02.14)*
